/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.SdkEmpty;
import io.swagger.model.SdkKeyValue;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-09-30T13:45:08.782-04:00")

@Api(value = "metadata", description = "the metadata API")
public interface MetadataApi {

    @ApiOperation(value = "Apply a Annotation to the backing GameServer metadata", nickname = "setAnnotation", notes = "", response = SdkEmpty.class, tags={ "SDK", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = SdkEmpty.class) })
    @RequestMapping(value = "/metadata/annotation",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<SdkEmpty> setAnnotation(@ApiParam(value = "" ,required=true )  @Valid @RequestBody SdkKeyValue body);


    @ApiOperation(value = "Apply a Label to the backing GameServer metadata", nickname = "setLabel", notes = "", response = SdkEmpty.class, tags={ "SDK", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = SdkEmpty.class) })
    @RequestMapping(value = "/metadata/label",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<SdkEmpty> setLabel(@ApiParam(value = "" ,required=true )  @Valid @RequestBody SdkKeyValue body);

}
